version: "2.22"

services:
  web:
    build:
      context: .
    container_name: news_crawler_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_media:/usr/src/app/media/
      - static:/static
    ports:
      - 8000:8000
    env_file:
      - ./NewsCrawler/NewsCrawler/.deploy.env
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: news_crawler_db
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=news_crawlerdb

volumes:
  db:
  app_media:
  static:
