# Generated by Django 5.0.6 on 2024-06-03 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0003_remove_customuser_email_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
