# Generated by Django 5.0.6 on 2024-06-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomRequestLogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customrequestlog',
            old_name='timestamp',
            new_name='create_date',
        ),
    ]
