# Generated by Django 5.0.6 on 2024-06-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomRequestLogs', '0002_rename_timestamp_customrequestlog_create_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequestlog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customrequestlog',
            name='requested_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
