# Generated by Django 5.0.6 on 2024-06-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('yjc_id', models.IntegerField()),
                ('pubDate_ad', models.DateTimeField()),
                ('pubDate_solar', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
