# Generated by Django 5.0.6 on 2024-06-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomNews', '0002_customnew_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnew',
            name='yjc_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
