# Generated by Django 5.0.6 on 2024-06-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomNews', '0003_alter_customnew_yjc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnew',
            name='status',
            field=models.CharField(choices=[('latest', 'latest'), ('most_visited', 'most_visited')], default='latest', max_length=20),
        ),
    ]
